#!/usr/bin/env python3
"""Render every case in ``tests/data/`` into ``tests/output/`` and index the result.

This is the proof sheet for the style profile. Edit a number in
``skills/scientific-figures/references/profiles/single-column.json``, run::

    python tests/render_gallery.py

and then look at ``tests/output/index.md`` (or the PNGs directly) to judge the
change. The cases are chosen so that every knob in the profile shows up in at
least one picture: the palette, the marker shapes, the dash-pattern channel that
takes over once colours run out, mathtext, and both bar sign cases.

The committed output is also the worked example of what a render produces: five
files per case, exactly as an agent would get them.
"""

from __future__ import annotations

import argparse
import os
import sys

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(TESTS_DIR)
SKILL_ROOT = os.path.join(REPO_ROOT, "skills", "scientific-figures")
sys.path.insert(0, os.path.join(SKILL_ROOT, "scripts"))

import figure_core  # noqa: E402
import render as render_module  # noqa: E402

DATA_DIR = os.path.join(TESTS_DIR, "data")
OUTPUT_DIR = os.path.join(TESTS_DIR, "output")

# Case name -> what this picture is here to let you judge.
CASES = {
    "scatter": "Two groups of unconnected samples: marker size, marker shapes, colour separation and legend scale. Every sample remains visible; no line or thinning.",
    "line-single": "One series: line width, marker size and spacing, tick and axis-label "
                   "sizes. No legend, because a single series names itself in the y label.",
    "line-multi": "Three series: the first three palette colours, their bound marker "
                  "shapes, and legend placement and size.",
    "line-many": "Eight series: colours 1-6, then colours 1-2 again with the dash pattern "
                 "taking over. Check that series 7 and 8 stay separable from 1 and 2.",
    "line-mathtext": "Mathtext labels and legend entries. Variables italic, units upright, "
                     "no LaTeX installation involved.",
    "bar-positive": "All-positive bars: they sit exactly on the baseline, one colour for "
                    "the one series, bar width and category label spacing.",
    "bar-signed": "Bars crossing zero: the zero line, symmetric padding, and a zero-valued "
                  "category that must still be visible as a category.",
}

STATUS_MARK = {"pass": "pass", "warn": "warn", "fail": "FAIL", "not_checked": "-"}


def case_names():
    return sorted(CASES)


def spec_path(name):
    return os.path.join(DATA_DIR, "%s.json" % name)


def case_output_dir(name):
    return os.path.join(OUTPUT_DIR, name)


def profile_summary(profile):
    """The handful of values worth seeing next to the pictures."""
    width_in, height_in = figure_core.figure_size_inches(profile)
    return [
        ("canvas.width_mm", profile["canvas"]["width_mm"]),
        ("canvas.aspect_ratio", profile["canvas"]["aspect_ratio"]),
        ("derived height (mm)", round(height_in * figure_core.MM_PER_INCH, 2)),
        ("fonts.family", profile["fonts"]["family"]),
        ("fonts.size_axis_label_pt", profile["fonts"]["size_axis_label_pt"]),
        ("fonts.size_tick_pt", profile["fonts"]["size_tick_pt"]),
        ("fonts.size_legend_pt", profile["fonts"]["size_legend_pt"]),
        ("lines.data_linewidth_pt", profile["lines"]["data_linewidth_pt"]),
        ("lines.axes_linewidth_pt", profile["lines"]["axes_linewidth_pt"]),
        ("lines.marker_size_pt", profile["lines"]["marker_size_pt"]),
        ("bar.width_fraction", profile["bar"]["width_fraction"]),
        ("output.png_dpi", profile["output"]["png_dpi"]),
    ]


def write_index(results, profile, profile_path):
    lines = [
        "# Style proof sheet",
        "",
        "Generated by `tests/render_gallery.py`. **Do not edit by hand** — edit the",
        "profile and re-run the script.",
        "",
        "Every value below is *provisional*: an initial project choice, not a journal or",
        "conference requirement. Change one, re-run, and compare the pictures.",
        "",
        "Profile: [`%s`](%s)"
        % (
            os.path.relpath(profile_path, REPO_ROOT),
            os.path.relpath(profile_path, OUTPUT_DIR).replace(os.sep, "/"),
        ),
        "",
        "| Key | Value |",
        "| --- | --- |",
    ]
    lines += ["| `%s` | %s |" % (key, value) for key, value in profile_summary(profile)]
    lines += [
        "",
        "Environment: matplotlib %s, Python %s."
        % (results[0]["report"]["environment"]["matplotlib"],
           results[0]["report"]["environment"]["python"]),
        "",
        "The PNGs below are 300 DPI previews, so on screen they are roughly four times",
        "the printed size. Judge legibility accordingly, or open the PDF at 100%.",
        "",
    ]

    for item in results:
        name = item["name"]
        report = item["report"]
        counts = report["counts"]
        lines += [
            "## %s" % name,
            "",
            CASES[name],
            "",
            "Checks: %d pass, %d warn, %d fail, %d not checked (`visual_review` is always "
            "the last of those — no script can close it)."
            % (counts["pass"], counts["warn"], counts["fail"], counts["not_checked"]),
            "",
        ]
        for check in report["checks"]:
            if check["status"] in ("warn", "fail"):
                lines.append("* **%s** — `%s`: %s" % (check["status"], check["id"], check["message"]))
        if any(check["status"] in ("warn", "fail") for check in report["checks"]):
            lines.append("")
        lines += [
            "![%s](%s/figure.png)" % (name, name),
            "",
            "Spec: [`tests/data/%s.json`](../data/%s.json) · "
            "PDF: [`%s/figure.pdf`](%s/figure.pdf) · "
            "Report: [`%s/report.json`](%s/report.json)"
            % (name, name, name, name, name, name),
            "",
        ]

    path = os.path.join(OUTPUT_DIR, "index.md")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines).rstrip() + "\n")
    return path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--profile",
        default=figure_core.default_profile_path(SKILL_ROOT),
        help="Profile to render the whole sheet with. Defaults to the skill's own.",
    )
    parser.add_argument("--case", action="append", help="Render only this case (repeatable).")
    args = parser.parse_args(argv)

    names = args.case or case_names()
    unknown = sorted(set(names) - set(CASES))
    if unknown:
        print("error: unknown case(s): %s" % ", ".join(unknown), file=sys.stderr)
        print("known cases: %s" % ", ".join(case_names()), file=sys.stderr)
        return 2

    profile = figure_core.load_profile(args.profile)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    results = []
    worst = "pass"
    for name in sorted(names):
        report = render_module.render(spec_path(name), case_output_dir(name), args.profile)
        results.append({"name": name, "report": report})
        counts = report["counts"]
        print(
            "%-16s %-5s  pass %2d  warn %d  fail %d"
            % (name, STATUS_MARK[report["status"]], counts["pass"], counts["warn"], counts["fail"])
        )
        for check in report["checks"]:
            if check["status"] in ("warn", "fail"):
                print("    [%s] %s: %s" % (check["status"], check["id"], check["message"]))
        if report["status"] == "fail" or (report["status"] == "warn" and worst == "pass"):
            worst = report["status"]

    index_path = write_index(results, profile, args.profile)
    print()
    print("proof sheet: %s" % os.path.relpath(index_path, REPO_ROOT))
    print("Now look at the PNGs. `visual_review` stays open until a person does.")
    return 1 if worst == "fail" else 0


if __name__ == "__main__":
    raise SystemExit(main())
