// Original illustrative prose for paper proportions; no experimental results are claimed.
export const PARAGRAPHS = [
  'We consider a comparative evaluation in which several methods are tested under a common experimental protocol. The same data preparation, training budget and evaluation procedure are used throughout. This makes it possible to examine differences between methods while keeping the surrounding conditions consistent. The accompanying figure provides a compact view of the quantities being compared.',
  'A curve can describe how a measured quantity changes over successive observations. Individual markers indicate the available measurements, while connecting lines make the overall trend easier to follow. When several curves share an axis, their labels identify the corresponding conditions. The interpretation depends on the units, the sampling procedure and the range of values displayed.',
  'Comparisons between named categories can instead be presented as bars. A shared baseline provides a consistent reference for reading their magnitudes. Positive and negative values describe changes in opposite directions relative to that reference. The order of the categories should remain consistent with the explanation in the text so that a reader can move easily between the discussion and the figure.',
  'For an empirical study, the experimental description should identify the data used, the evaluation setting and any sources of variation. Repeated measurements can help distinguish a systematic difference from variability in the procedure. A visual comparison provides context for the analysis, while numerical summaries and an explicit account of uncertainty support the conclusions drawn from it.',
  'The relationship between local behavior and the overall trend is also relevant. A difference near the beginning of a sequence may diminish at later observations, while a small but persistent separation may remain visible across the full range. Reading the entire axis helps avoid placing too much emphasis on a single point. Any interpretation should be considered alongside the conditions under which the observations were collected.',
  'When a figure contains multiple panels, each panel can address a related aspect of the comparison. A common set of labels and a consistent visual style help connect these views. The caption should explain what each panel represents, and the surrounding discussion should make clear why the views are shown together. The reader can then compare individual details without losing the broader experimental context.',
  'A complete report also describes the limitations of the comparison. Differences in data coverage, measurement conditions or the range of tested settings can affect how broadly an observation applies. These details are best stated alongside the main findings. The figure serves as a concise account of the displayed measurements, and the text supplies the context needed to interpret them.',
];
